import {
  RESOURCE_MIME_TYPE,
  registerAppResource,
  registerAppTool,
} from "@modelcontextprotocol/ext-apps/server";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { ReadResourceResult } from "@modelcontextprotocol/sdk/types.js";
import crypto from "node:crypto";
import fs from "node:fs/promises";
import fsSync from "node:fs";
import path from "node:path";
import { z } from "zod";
import type { BrickDefinition } from "./src/bricks/types.js";
import { parseLDrawPart, setLDrawDir } from "./src/ldraw/ldraw-dimensions.js";
import { OccupancyGrid, computeOccupiedCells, computeCollisionCells, computeBottomCells } from "./src/engine/OccupancyGrid.js";

// Initialize LDraw directory for the server-side parser
const LDRAW_DIR = path.join(
  import.meta.filename.endsWith(".ts") ? import.meta.dirname : path.join(import.meta.dirname, ".."),
  "ldraw",
);
setLDrawDir(LDRAW_DIR);

const DIST_DIR = import.meta.filename.endsWith(".ts")
  ? path.join(import.meta.dirname, "dist")
  : import.meta.dirname;

// ── LDraw parts index (generated by scripts/generate-parts-index.ts) ────────

interface PartsIndexEntry {
  id: string;
  name: string;
}

interface PartsIndex {
  categories: Record<string, PartsIndexEntry[]>;
  totalParts: number;
  generatedAt: string;
}

let partsIndex: PartsIndex = { categories: {}, totalParts: 0, generatedAt: "" };
let allParts: { id: string; name: string; category: string }[] = [];

try {
  const indexPath = path.join(
    import.meta.filename.endsWith(".ts") ? import.meta.dirname : path.join(import.meta.dirname, ".."),
    "ldraw-parts-index.json",
  );
  const raw = fsSync.readFileSync(indexPath, "utf-8");
  partsIndex = JSON.parse(raw) as PartsIndex;
  for (const [category, parts] of Object.entries(partsIndex.categories)) {
    for (const part of parts) {
      allParts.push({ id: part.id, name: part.name, category });
    }
  }
  console.error(`Loaded LDraw parts index: ${partsIndex.totalParts} parts across ${Object.keys(partsIndex.categories).length} categories`);
} catch {
  console.warn("LDraw parts index not found — brick_search_parts will return empty results. Run 'npm run generate:index' to generate it.");
}

function findBrickType(typeId: string): BrickDefinition | undefined {
  return parseLDrawPart(typeId) ?? undefined;
}

// Popular LDraw part IDs for brick_get_available
const POPULAR_PART_IDS = [
  // Standard Bricks
  '3005', '3004', '3622', '3010', '3009', '3008',
  '3003', '3002', '3001', '2456', '3007',
  // Plates
  '3024', '3023', '3710', '3022', '3020', '3795',
  '3031', '3958', '3036', '3035', '4477',
  // Slopes
  '3039', '3040', '3665', '3660',
  // Technic
  '3700', '3701', '3894', '3702', '3709',
  // Corner
  '2357', '2462',
];

// ── Types ────────────────────────────────────────────────────────────────────

interface BrickInstance {
  id: string;
  typeId: string;
  position: { x: number; y: number; z: number };
  rotation: 0 | 90 | 180 | 270;
  color: string;
}

interface SceneData {
  name: string;
  bricks: BrickInstance[];
}

interface AABB {
  minX: number; maxX: number;
  minY: number; maxY: number;
  minZ: number; maxZ: number;
}

// ── Occupancy grid (authoritative collision detection) ───────────────────────

const grid = new OccupancyGrid();

// ── AABB helpers (used for footprint reporting and bounds checking) ──────────

function getBrickAABB(brick: BrickInstance, brickType: BrickDefinition): AABB {
  if (brickType.occupancyMap) {
    // Derive footprint from actual occupied cells (handles non-rectangular parts)
    const cells = computeOccupiedCells(brick as any, brickType);
    let minX = Infinity, maxX = -Infinity;
    let minY = Infinity, maxY = -Infinity;
    let minZ = Infinity, maxZ = -Infinity;
    for (const c of cells) {
      if (c.x < minX) minX = c.x;
      if (c.x + 1 > maxX) maxX = c.x + 1;
      if (c.y < minY) minY = c.y;
      if (c.y + 1 > maxY) maxY = c.y + 1;
      if (c.z < minZ) minZ = c.z;
      if (c.z + 1 > maxZ) maxZ = c.z + 1;
    }
    return { minX, maxX, minY, maxY, minZ, maxZ };
  }
  const { x, y, z } = brick.position;
  const isRotated = brick.rotation === 90 || brick.rotation === 270;
  const sx = isRotated ? brickType.studsZ : brickType.studsX;
  const sz = isRotated ? brickType.studsX : brickType.studsZ;
  return {
    minX: x, maxX: x + sx,
    minY: y, maxY: y + brickType.heightUnits,
    minZ: z, maxZ: z + sz,
  };
}

function checkCollision(
  _bricks: BrickInstance[],
  newBrick: BrickInstance,
  newType: BrickDefinition,
  excludeId?: string,
): boolean {
  const cells = computeCollisionCells(newBrick, newType);
  return !grid.canPlace(cells, excludeId);
}

// ── Baseplate bounds ─────────────────────────────────────────────────────────

const BASEPLATE_SIZE = 48;

// ── Batch limits ────────────────────────────────────────────────────────────
// The host enforces a ~5MB cap on the burst of tool traffic following the
// first scene render. Each new typeId triggers a brick_get_ldraw_files fetch
// (up to ~1.6MB/part on the wire). Capping new types per batch keeps that
// burst bounded; the row cap bounds the brick_place response itself.

const MAX_BATCH_ROWS = 200;
const MAX_NEW_TYPES_PER_BATCH = 10;

function checkBounds(
  brick: BrickInstance,
  brickType: BrickDefinition,
): { error: string; suggestedX?: number; suggestedZ?: number; suggestedY?: number } | null {
  const aabb = getBrickAABB(brick, brickType);
  const spanX = aabb.maxX - aabb.minX;
  const spanZ = aabb.maxZ - aabb.minZ;
  if (aabb.maxX > BASEPLATE_SIZE) {
    return {
      error: `Brick extends outside baseplate on X axis (valid: 0–${BASEPLATE_SIZE - 1})`,
      suggestedX: BASEPLATE_SIZE - spanX,
    };
  }
  if (aabb.minX < 0) {
    return {
      error: `Brick extends outside baseplate on X axis (valid: 0–${BASEPLATE_SIZE - 1})`,
      suggestedX: 0,
    };
  }
  if (aabb.maxZ > BASEPLATE_SIZE) {
    return {
      error: `Brick extends outside baseplate on Z axis (valid: 0–${BASEPLATE_SIZE - 1})`,
      suggestedZ: BASEPLATE_SIZE - spanZ,
    };
  }
  if (aabb.minZ < 0) {
    return {
      error: `Brick extends outside baseplate on Z axis (valid: 0–${BASEPLATE_SIZE - 1})`,
      suggestedZ: 0,
    };
  }
  if (aabb.minY < 0) {
    return { error: "Brick is below the baseplate", suggestedY: 0 };
  }
  return null;
}

/** Find the first existing brick whose cells this brick would collide with. */
function findCollisionBlocker(
  brick: BrickInstance,
  brickType: BrickDefinition,
): { id: string; typeId: string; footprint: { minX: number; maxX: number; minZ: number; maxZ: number; topY: number } } | null {
  const cells = computeCollisionCells(brick, brickType);
  for (const c of cells) {
    const occupantId = grid.getOccupantAt(c.x, c.y, c.z);
    if (occupantId) {
      const blocker = scene.bricks.find(b => b.id === occupantId);
      if (!blocker) return null;
      const bt = findBrickType(blocker.typeId);
      if (!bt) return null;
      const aabb = getBrickAABB(blocker, bt);
      return {
        id: blocker.id,
        typeId: blocker.typeId,
        footprint: { minX: aabb.minX, maxX: aabb.maxX, minZ: aabb.minZ, maxZ: aabb.maxZ, topY: aabb.maxY },
      };
    }
  }
  return null;
}

/** Scan +X then +Z for the nearest open slot at this brick's Y. Never suggests out-of-bounds. */
function scanForOpenSlot(
  brick: BrickInstance,
  brickType: BrickDefinition,
): { suggestedX?: number; suggestedZ?: number } {
  const MAX_SCAN = 8;
  for (let dx = 1; dx <= MAX_SCAN; dx++) {
    const probe: BrickInstance = { ...brick, position: { ...brick.position, x: brick.position.x + dx } };
    if (checkBounds(probe, brickType)) break;
    if (!checkCollision(scene.bricks, probe, brickType)) return { suggestedX: probe.position.x };
  }
  for (let dz = 1; dz <= MAX_SCAN; dz++) {
    const probe: BrickInstance = { ...brick, position: { ...brick.position, z: brick.position.z + dz } };
    if (checkBounds(probe, brickType)) break;
    if (!checkCollision(scene.bricks, probe, brickType)) return { suggestedZ: probe.position.z };
  }
  return {};
}

function checkSupport(_bricks: BrickInstance[], brick: BrickInstance, brickType: BrickDefinition): boolean {
  return grid.hasSupport(brick, brickType);
}

/**
 * Find the highest Y where this brick's footprint would rest on existing support.
 * Scans each XZ column in the brick's bottom footprint downward from just below
 * the requested y. Returns max(top-of-highest-occupant) across columns, or 0.
 */
function findLandingY(brick: BrickInstance, brickType: BrickDefinition): number {
  const bottomCells = computeBottomCells(brick, brickType);
  let landingY = 0;
  for (const c of bottomCells) {
    for (let checkY = brick.position.y - 1; checkY >= 0; checkY--) {
      if (grid.getOccupantAt(c.x, checkY, c.z)) {
        if (checkY + 1 > landingY) landingY = checkY + 1;
        break;
      }
    }
  }
  return landingY;
}

function findUnsupported(bricks: BrickInstance[]): string[] {
  // Rebuild a temporary grid from remaining bricks to check support
  const tempGrid = new OccupancyGrid();
  tempGrid.rebuild(bricks, (id) => findBrickType(id) ?? undefined);
  const unsupported: string[] = [];
  for (const brick of bricks) {
    const bt = findBrickType(brick.typeId);
    if (!bt) continue;
    if (!tempGrid.hasSupport(brick, bt)) {
      unsupported.push(brick.id);
    }
  }
  return unsupported;
}

function generateId(): string {
  return crypto.randomUUID();
}

// ── Server factory ───────────────────────────────────────────────────────────

const resourceUri = "ui://brick-builder/mcp-app.html";

// ── Brick cheat sheet (returned by brick_read_me) ───────────────────────────

function buildCatalogCheatSheet(): string {
  let sheet = `# Brick Builder Reference

You only need to call brick_read_me once. Do NOT call it again — you will not see anything new.

## Order of Operations (MANDATORY — follow exactly)
1. brick_read_me → Call once to learn the building format and rules (you just did this)
2. brick_get_available → Returns a starter set of popular parts AND a category index of the full ${partsIndex.totalParts}-part library
   - brick_search_parts → Get any category or search by name. Results include dimensions (studsX, studsZ, heightUnits) so you can brick_place directly. Example: brick_search_parts({category: "Arch"}) returns all arches; brick_search_parts({query: "corner"}) finds corner parts across categories.
3. brick_render_scene → Call BEFORE placing any bricks. Opens the 3D viewer. If you skip this step, the user cannot see anything you build.
4. brick_place → Place one or many bricks via CSV (one row per brick). They stream into the viewer live, row by row, as the tool runs. Batch cap: ${MAX_BATCH_ROWS} rows / ${MAX_NEW_TYPES_PER_BATCH} new part types per call — for large builds, call it multiple times with chunks.
5. brick_get_scene → Call anytime to inspect what's currently built
6. brick_remove_brick → Remove a specific brick by ID (use brick_get_scene to find IDs). Also removes unsupported bricks above it.
7. brick_clear_scene → Call to remove all bricks and start over

CRITICAL: You must call brick_render_scene before your first brick_place call. Placing bricks without rendering the scene first means the user has no viewer open and sees nothing.

## Brick Types
Any LDraw part number works as a typeId. brick_get_available gives you ~30 starters plus the full category index. brick_search_parts gives you any category or name match with dimensions included — use it whenever you want a shape that isn't in the starter set. Example: need an arch for a doorway → brick_search_parts({category: "Arch"}) → pick one → brick_place.

## Beyond standard bricks — specialty parts

The library has ${partsIndex.totalParts} parts across ${Object.keys(partsIndex.categories).length} categories.
Beyond the basic bricks/plates/slopes, reach for brick_search_parts to get:

| Category | Count | Use for |
|---|---|---|
| Arch | ~${partsIndex.categories['Arch']?.length ?? 0} | Doorways, bridges, curved openings |
| Door | ~${partsIndex.categories['Door']?.length ?? 0} | Building facades, entrances |
| Window | ~${partsIndex.categories['Window']?.length ?? 0} | Building facades, glazing |
| Panel | ~${partsIndex.categories['Panel']?.length ?? 0} | Thin walls, greebling |
| Fence | ~${partsIndex.categories['Fence']?.length ?? 0} | Railings, barriers |
| Wheel | ~${partsIndex.categories['Wheel']?.length ?? 0} | Vehicles (see relaxed mode below) |
| Tyre | ~${partsIndex.categories['Tyre']?.length ?? 0} | Vehicles (see relaxed mode below) |
| Hinge | ~${partsIndex.categories['Hinge']?.length ?? 0} | Articulated joints |
| Minifig | ~${partsIndex.categories['Minifig']?.length ?? 0} | Characters |
| Minifig Accessory | ~${partsIndex.categories['Minifig Accessory']?.length ?? 0} | Held items, props |

Example: brick_search_parts({category: "Arch"}) → returns all arches with dimensions ready for brick_place.

## Coordinate System
- Baseplate: ${BASEPLATE_SIZE}×${BASEPLATE_SIZE} studs on the X and Z axes
- Y axis: height in plate units (1 standard brick = 3 Y units, 1 plate = 1 Y unit)
- Valid ranges: X 0–${BASEPLATE_SIZE - 1}, Z 0–${BASEPLATE_SIZE - 1}, Y 0+
- Compass: -X is East, +X is West, +Z is North, -Z is South. The viewer shows a 3D axes gizmo (bottom-right, red=X green=Y blue=Z) so the human can see which screen direction is which axis while orbiting.
- Rotation: "0", "90", "180", or "270" (string)
- In strict mode (default), bricks CANNOT float — they must sit on the baseplate (Y=0) or on top of another brick. In relaxed mode, floating is allowed (see Build Modes).
- ALL positions are relative to the baseplate. A brick's entire footprint (position + size) must stay within the ${BASEPLATE_SIZE}×${BASEPLATE_SIZE} baseplate. Out-of-bounds placements are rejected.
- A brick at position (x, z) with studsX=2, studsZ=4 occupies x to x+2, z to z+4. So the maximum valid x for that brick is ${BASEPLATE_SIZE - 2}, and the maximum valid z is ${BASEPLATE_SIZE - 4}.
- IMPORTANT: Every brick_place response includes a per-row "footprint" showing each brick's exact occupied area: {minX, maxX, minZ, maxZ, topY}. Use footprint.maxX/maxZ to know where to place the NEXT brick adjacent to it. Use footprint.topY for the Y value of the next layer on top.
- You can batch many bricks in one brick_place call (one CSV row each). When tiling with a known dimension (e.g. 3001 is 2×4 → z advances by 4), compute the whole batch up front. When unsure of a part's footprint, place it alone first and read the response.
- brick_get_scene also returns footprints for every brick. ALWAYS read footprints to position new bricks — never calculate positions from scratch when existing bricks have footprints.

## Size & Scale Reference

Height is measured in bricks (1 brick = 3 plates = 3 Y units).
| Category       | Height        | Real-world approx |
|----------------|---------------|-------------------|
| Short          | 1–10 bricks   | up to ~9.6 cm     |
| Medium         | 11–30 bricks  | ~10–28 cm         |
| Tall           | 31–60 bricks  | ~29–57 cm         |
| Tower/Skyscraper | 60+ bricks | 57 cm+            |

Short builds sit flat on a table and are viewed mostly from above (vehicles, small vignettes, garden scenes). Medium builds are eye-catching at table height and viewed straight-on. Tall builds demand vertical presence and often need internal reinforcement.

Width is measured in studs (1 stud = 8 mm).
| Category | Width       | Real-world approx |
|----------|-------------|-------------------|
| Narrow   | 1–8 studs   | up to ~6.4 cm     |
| Medium   | 9–24 studs  | ~7–19 cm          |
| Wide     | 25–48 studs | ~20–38 cm         |
| Massive  | 48+ studs   | 38 cm+            |

Narrow builds are things like a single tower, a lamppost, or a small character model. Medium is the sweet spot for most standalone builds — a small house, a vehicle, a diorama scene. Wide and massive are dioramas, modular-style buildings, and layout sections.

## Colors
Red #cc0000 · Blue #0055bf · Green #237841 · Yellow #f2cd37 · White #ffffff · Black #1b2a34
Orange #fe8a18 · Brown #583927 · Tan #e4cd9e · Dark grey #6b5a5a · Light grey #9ba19d · Dark blue #0a3463

## Footprints

Every brick_place response and brick_get_scene response includes a "footprint" for each brick:
  { minX, maxX, minZ, maxZ, topY }

This tells you the exact area the brick occupies on the baseplate after rotation is applied.
- minX/maxX: the brick spans from minX to maxX along the X axis
- minZ/maxZ: the brick spans from minZ to maxZ along the Z axis
- topY: the top of the brick — use this as the Y value for stacking a brick on top

Use footprints to position new bricks. Do NOT calculate positions manually — read the footprint from the response.
- To place a brick adjacent along X: use the previous brick's footprint.maxX as the new brick's x
- To place a brick adjacent along Z: use the previous brick's footprint.maxZ as the new brick's z
- To stack on top: use the previous brick's footprint.topY as the new brick's y

Example: you place a 2x4 brick (typeId="3001") at (10, 0, 10) with rotation "90". The response includes:
  footprint: { minX: 10, maxX: 14, minZ: 10, maxZ: 12, topY: 3 }
To place the next brick to the right: x=14 (footprint.maxX)
To place a brick in front: z=12 (footprint.maxZ)
To stack on top: y=3 (footprint.topY)

## Orientation of asymmetric parts (slopes, wedges, arches)

LDraw parts are rotated -90° around Y on load, so their native "front" (LDraw -Z) becomes our +X.
At rotation=0, the studded/solid end of an asymmetric part sits at the LOW-X side of its footprint. The sloped/open/pointy feature faces +X.

Our rotation is COUNTER-CLOCKWISE looking down (+Y view). Each +90 turns the feature from +X → +Z → -X → -Z → +X.

| rotation | feature faces | studs at | top-down view (S=stud, /=slope) |
|----------|---------------|----------|---------------------------------|
| 0        | +X            | low-X    | S /   (slope on the +X side)    |
| 90       | +Z            | low-Z    | S over /  (slope on the +Z side)|
| 180      | -X            | high-X   | / S   (slope on the -X side)    |
| 270      | -Z            | high-Z   | / over S  (slope on the -Z side)|

CRITICAL: if your 0/180 slopes look right but your 90/270 slopes point the wrong way, you have them swapped — use 90 where you used 270 and vice versa. Our 90 is COUNTER-CLOCKWISE, not clockwise.

### Roof peak — ridge runs along Z (slopes face each other across X)
  brick_place(bricks="3039,10,3,10,0,#cc0000
  3039,14,3,10,180,#cc0000")
    # Slope at x=10 (rotation=0) faces +X. Slope at x=14 (rotation=180) faces -X. They meet at x=12.

### Roof peak — ridge runs along X (slopes face each other across Z)
  brick_place(bricks="3039,10,3,10,90,#cc0000
  3039,10,3,14,270,#cc0000")
    # Slope at z=10 (rotation=90) faces +Z. Slope at z=14 (rotation=270) faces -Z. They meet at z=12.

### Four-sided pyramid roof (slopes on all sides facing INWARD)
  # Building center at (x=15, z=15). Each slope faces TOWARD the center.
  # East slope (low-X side, x=10): needs to face +X (toward center) → rotation=0
  # West slope (high-X side, x=18): needs to face -X (toward center) → rotation=180
  # South slope (low-Z side, z=10): needs to face +Z (toward center) → rotation=90
  # North slope (high-Z side, z=18): needs to face -Z (toward center) → rotation=270

## Examples

brick_place takes CSV: typeId,x,y,z,rotation,color — one brick per line. Rows are auto-sorted by Y ascending before placement, so you don't have to order supports first — but each brick still needs valid Y (on baseplate or resting on an existing brick).

### Single brick
  brick_place(bricks="3001,10,0,10,0,#cc0000")
    → results[0].footprint: {minX:10, maxX:12, minZ:10, maxZ:14, topY:3}

### Wall (4 bricks tall, one call — streams into viewer row by row)
3008 = Brick 1x8, heightUnits=3 → y advances by 3 per layer:
  brick_place(bricks="3008,10,0,10,0,#cc0000
  3008,10,3,10,0,#cc0000
  3008,10,6,10,0,#cc0000
  3008,10,9,10,0,#cc0000")
    → results: [{row:1, ok:true, footprint:{...topY:3}}, {row:2, ok:true, footprint:{...topY:6}}, ...]

### Row along Z (one call)
3001 = Brick 2x4, studsZ=4 → z advances by 4:
  brick_place(bricks="3001,10,0,10,0,#cc0000
  3001,10,0,14,0,#0055bf
  3001,10,0,18,0,#237841")

### Row along X (one call)
3001 studsX=2 → x advances by 2:
  brick_place(bricks="3001,10,0,10,0,#cc0000
  3001,12,0,10,0,#0055bf
  3001,14,0,10,0,#237841")

### Unknown part dimensions → place one, read footprint, then batch
  brick_place(bricks="3003,20,0,20")                      ← 3003 = ? place alone
    → results[0].footprint: {minX:20, maxX:22, minZ:20, maxZ:22, topY:3}   (it's 2×2)
  brick_place(bricks="3003,22,0,20\\n3003,24,0,20\\n3003,26,0,20")   ← now batch with x+=2

### Rotation changes footprint — always read it
  3001 (Brick 2x4) at rotation "0":  footprint maxX = x+2, maxZ = z+4
  3001 (Brick 2x4) at rotation "90": footprint maxX = x+4, maxZ = z+2  (swapped!)

## Build modes

- **strict** (default) — every brick needs support (y=0 or resting on a brick below). Removing a support cascades: everything above it that loses support is also removed. Use for structurally realistic builds.
- **relaxed** — skips the support requirement. Floating bricks are allowed (placement still returns a \`warnings: ["floating"]\` hint). Removing a brick does NOT cascade. Use for staged assembly (place wheels before axles), specialty parts that attach via pins/clips, or freeform artistic builds.

- **snap** (orthogonal flag) — when a brick lacks support, auto-correct its y to the nearest landing instead of rejecting. Works in both strict and relaxed mode. Result row includes \`snappedFrom:{y:originalY}\` and a warning. Turn on for layer-by-layer builds where you trust the server's landing math.

Switch with: brick_set_build_mode({mode: "relaxed"})
Set snap with: brick_set_build_mode({snap: true})
Both can be set together: brick_set_build_mode({mode: "strict", snap: true})
Check current mode: brick_get_scene includes \`buildMode\` and \`snap\` in the scene data.

Typical workflow for vehicles:
1. brick_set_build_mode({mode: "relaxed"})
2. brick_search_parts({category: "Wheel"}) → find a wheel
3. brick_place with wheels at the right height (they'll float until step 4)
4. brick_place the chassis/axle bricks — wheels now visually connect
5. brick_set_build_mode({mode: "strict"}) to resume normal building

## Rules
- In strict mode (default), every brick needs support: y=0 (baseplate) OR resting on top of another brick. Floating bricks are rejected with a suggestedY hint. In relaxed mode, floating is allowed — see Build Modes above.
- Use typeId values from brick_get_available for popular parts. You can also use any LDraw part number — the server will auto-detect dimensions from the LDraw library.
- brick_place returns {summary:{placed,failed,deferred?,totalBricks,hints?}, results:[...]}. Each row result is either {ok:true, id, footprint, snappedFrom?} or {ok:false, error, line, suggestedY?, suggestedX?, suggestedZ?, collidingWith?}. Rows are auto-sorted by Y before processing. If a row fails support, its error includes suggestedY — the nearest valid landing height. Retry that row with y=suggestedY (or enable snap mode to auto-land). If several rows fail, collect all of them, apply each hint, and resend them together in ONE follow-up call — don't retry one row at a time.
- Collision errors include \`collidingWith: {id, typeId, footprint}\` — use footprint.maxX or footprint.maxZ to retry adjacent to the blocker. May also include \`suggestedX\` or \`suggestedZ\` (nearest open slot within 8 studs).
- Bounds errors include \`suggestedX\`/\`suggestedZ\`/\`suggestedY\` — the nearest in-bounds position for this brick's actual footprint (rotation-aware).
- Batch cap: max ${MAX_BATCH_ROWS} rows AND max ${MAX_NEW_TYPES_PER_BATCH} new part types per brick_place call. Rows beyond either cap are deferred — their error says "Batch cap reached" and summary.deferred counts them. Just resend those rows in the next brick_place call. Reusing a typeId already in the scene doesn't count toward the new-types cap.
- Rotation swaps dimensions — account for this when tiling.
- ALL bricks must fit within the ${BASEPLATE_SIZE}×${BASEPLATE_SIZE} baseplate. The brick's full footprint (position + studs size) must not exceed x=${BASEPLATE_SIZE - 1} or z=${BASEPLATE_SIZE - 1}. Out-of-bounds placements are rejected.
- Every successful row in brick_place results includes a footprint — use results[i].footprint.topY to position the next layer. You don't need brick_get_scene between your own brick_place calls; only call it at the START of a task to see what prior turns or the human placed.

## Building Strategy
1. Call brick_get_scene ONCE at the start to see what's already built. After that, track positions from the footprints in each brick_place results array.
2. Plan the footprint first — lay the ground floor (Y=0)
3. Build upward layer by layer — each layer's Y = previous Y + heightUnits
4. Send ~10 rows per brick_place call — one small section at a time. Never generate the whole build's CSV up front; plan the next section from the footprints returned in results. Rows are Y-sorted before processing so supports within a chunk land first.
5. Alternate brick offsets between rows for realistic interlocking
6. Use plates (heightUnits=1) for thin details, trim, and floors
7. Use slopes for rooflines — studs are only on the flat side
8. Build in sections: foundation → walls → roof

## Best Practices
- Work at a scale that makes sense for the detail level you want. Larger scale gives more room for realism.
- Plan your color scheme early. Mixing too many colors by accident is a common mistake — pick 2-3 main colors and 1-2 accent colors.
- Overlap your layers like real brickwork — never stack bricks where joints align vertically. That creates weak seam lines. Offset by half a brick length on alternating rows.
- Distribute weight evenly and think about the base. Wide, flat bases are more stable than tall narrow towers without internal reinforcement.
- Use Technic bricks internally for rigid structural support, especially in large builds.
- Use consistent lighting logic — if your build has a light source, shade the darker side with darker colored bricks.
- Finish exposed surfaces with plates for a clean, polished look. Use slopes for angled surfaces and rooflines.
- For sci-fi and industrial builds, add small technical-looking details (greebling) with 1x1 bricks and plates, but apply with restraint so it doesn't look random.
- Don't be afraid to use brick_clear_scene and rebuild. The best builders redo sections many times.
- Step back and consider the build from the intended viewing angle, not just from above.
`;

  return sheet;
}

// Shared scene state — the host creates separate MCP sessions for the LLM
// and the app iframe, so per-closure state won't be visible across both.
// Module-level state ensures both sessions read/write the same scene.
let scene: SceneData = { name: "Untitled", bricks: [] };

type BuildMode = 'strict' | 'relaxed';
let buildMode: BuildMode = 'strict';
let snapY: boolean = false;

export function createServer(): McpServer {
  const server = new McpServer({
    name: "Brick Builder",
    version: "1.0.0",
  }, {
    instructions: `3D brick construction tool. IMPORTANT: Always call brick_read_me first to learn available brick types and their dimensions before building anything. Brick type IDs are LDraw part numbers (e.g. "3001" = Brick 2x4). Call brick_get_available to see popular parts, but you can also use any valid LDraw part number — dimensions are auto-detected.`,
  });

  function collectDynamicTypes(): Record<string, BrickDefinition> | undefined {
    const dynamic: Record<string, BrickDefinition> = {};
    for (const brick of scene.bricks) {
      if (!dynamic[brick.typeId]) {
        const def = findBrickType(brick.typeId);
        if (def) dynamic[brick.typeId] = def;
      }
    }
    return Object.keys(dynamic).length > 0 ? dynamic : undefined;
  }

  function scenePayload(message?: string) {
    const dynamicTypes = collectDynamicTypes();
    return {
      scene: {
        ...scene,
        buildMode,
        snap: snapY,
        ...(dynamicTypes ? { dynamicTypes } : {}),
      },
      ...(message ? { message } : {}),
    };
  }

  function sceneResult(message?: string) {
    const payload = scenePayload(message);
    return {
      content: [{ type: "text" as const, text: JSON.stringify(payload) }],
    };
  }

  function sceneWithFootprints() {
    const bricksWithFootprints = scene.bricks.map(b => {
      const bt = findBrickType(b.typeId);
      if (!bt) return b;
      const aabb = getBrickAABB(b, bt);
      return {
        ...b,
        footprint: { minX: aabb.minX, maxX: aabb.maxX, minZ: aabb.minZ, maxZ: aabb.maxZ, topY: aabb.maxY },
      };
    });
    const dynamicTypes = collectDynamicTypes();
    return {
      ...scene,
      bricks: bricksWithFootprints,
      buildMode,
      snap: snapY,
      ...(dynamicTypes ? { dynamicTypes } : {}),
    };
  }

  // ── Tool 1: brick_read_me (model-only, no frame) ───────────────────────

  server.registerTool(
    "brick_read_me",
    {
      description: "Returns the building guide, coordinate system, and examples. Call this BEFORE using any other brick tool for the first time.",
      annotations: { readOnlyHint: true },
    },
    async () => ({
      content: [{ type: "text" as const, text: buildCatalogCheatSheet() }],
    }),
  );

  // ── Tool 2: brick_get_available (model-only, no frame) ────────────────

  server.registerTool(
    "brick_get_available",
    {
      description: "Returns popular brick types with their IDs and dimensions. You can also use any LDraw part number not listed here. For the full library (15,000+ parts), use brick_search_parts to search or browse by category. Call this to learn what bricks you can use before building.",
      annotations: { readOnlyHint: true },
    },
    async () => {
      const parts: { typeId: string; name: string; studsX: number; studsZ: number; heightUnits: number }[] = [];
      for (const partId of POPULAR_PART_IDS) {
        const def = parseLDrawPart(partId);
        if (def) {
          parts.push({
            typeId: def.id,
            name: def.name,
            studsX: def.studsX,
            studsZ: def.studsZ,
            heightUnits: def.heightUnits,
          });
        }
      }
      const categories = Object.entries(partsIndex.categories)
        .map(([name, list]) => ({ name, count: list.length }))
        .sort((a, b) => b.count - a.count);
      const result = {
        parts,
        categories,
        totalParts: partsIndex.totalParts,
        note: `The ${parts.length} parts above are a curated starter set. The full library has ${partsIndex.totalParts} parts across ${categories.length} categories (see 'categories' above). To get any category with dimensions, call brick_search_parts({category: "Slope"}) or search by name with brick_search_parts({query: "corner"}). All results include studsX/studsZ/heightUnits ready for brick_place.`,
      };
      return { content: [{ type: "text" as const, text: JSON.stringify(result) }] };
    },
  );

  // ── Tool 2b: brick_search_parts (model-only, no frame) ─────────────────

  server.registerTool(
    "brick_search_parts",
    {
      description:
        "Search or browse the full LDraw parts library. Without arguments, returns all categories with part counts. Use 'query' to search by name, 'category' to browse a specific category, or both to search within a category. Results are paginated.",
      inputSchema: {
        query: z.string().optional().describe("Search term to match against part names (case-insensitive substring match)"),
        category: z.string().optional().describe("Filter to a specific category (e.g. 'Brick', 'Plate', 'Slope')"),
        offset: z.number().int().min(0).optional().default(0).describe("Pagination offset (default 0)"),
        limit: z.number().int().min(1).max(50).optional().default(25).describe("Results per page (default 25, max 50)"),
      },
      annotations: { readOnlyHint: true },
    },
    async ({ query, category, offset, limit }) => {
      const off = offset ?? 0;
      const lim = limit ?? 25;

      // No query, no category → list all categories with counts
      if (!query && !category) {
        const categoryList = Object.entries(partsIndex.categories)
          .map(([name, parts]) => ({ name, count: parts.length }))
          .sort((a, b) => b.count - a.count);
        return {
          content: [{
            type: "text" as const,
            text: JSON.stringify({
              totalParts: partsIndex.totalParts,
              categories: categoryList,
              hint: "Use 'category' to browse parts in a category, or 'query' to search by name.",
            }),
          }],
        };
      }

      // Filter parts
      let results: { id: string; name: string; category: string }[];
      if (category && !query) {
        // Browse a specific category
        const parts = partsIndex.categories[category];
        if (!parts) {
          // Try case-insensitive match
          const match = Object.keys(partsIndex.categories).find(
            (c) => c.toLowerCase() === category.toLowerCase(),
          );
          if (match) {
            results = partsIndex.categories[match].map((p) => ({ ...p, category: match }));
          } else {
            return {
              content: [{
                type: "text" as const,
                text: JSON.stringify({
                  error: `Category "${category}" not found.`,
                  availableCategories: Object.keys(partsIndex.categories).sort(),
                }),
              }],
              isError: true,
            };
          }
        } else {
          results = parts.map((p) => ({ ...p, category }));
        }
      } else if (query && !category) {
        // Search all parts by name
        const q = query.toLowerCase();
        results = allParts.filter((p) => p.name.toLowerCase().includes(q));
      } else {
        // Search within a specific category
        const q = query!.toLowerCase();
        const catName =
          partsIndex.categories[category!]
            ? category!
            : Object.keys(partsIndex.categories).find(
                (c) => c.toLowerCase() === category!.toLowerCase(),
              );
        if (!catName || !partsIndex.categories[catName]) {
          return {
            content: [{
              type: "text" as const,
              text: JSON.stringify({
                error: `Category "${category}" not found.`,
                availableCategories: Object.keys(partsIndex.categories).sort(),
              }),
            }],
            isError: true,
          };
        }
        results = partsIndex.categories[catName]
          .filter((p) => p.name.toLowerCase().includes(q))
          .map((p) => ({ ...p, category: catName }));
      }

      const total = results.length;
      const page = results.slice(off, off + lim).map((p) => {
        const def = parseLDrawPart(p.id);
        return def
          ? { ...p, studsX: def.studsX, studsZ: def.studsZ, heightUnits: def.heightUnits }
          : p;
      });

      return {
        content: [{
          type: "text" as const,
          text: JSON.stringify({
            results: page,
            total,
            offset: off,
            limit: lim,
            hasMore: off + lim < total,
          }),
        }],
      };
    },
  );

  // ── Tool 2c: brick_get_ldraw_files (app-only) ──────────────────────────
  // The MCP App iframe inside Claude has no HTTP origin, so relative fetches
  // to /ldraw/*.dat fail. This tool delivers the part file plus every
  // transitive subfile reference so LDrawLoader can resolve them from blob URLs.

  function collectLDrawFiles(partId: string): Record<string, string> | null {
    const entry = path.join(LDRAW_DIR, "parts", `${partId}.dat`);
    if (!fsSync.existsSync(entry)) return null;

    const files: Record<string, string> = {};

    const resolveSub = (parentPath: string, ref: string): string | null => {
      const normalized = ref.replace(/\\/g, "/");
      const parentDir = path.dirname(parentPath);
      const candidates = [
        path.join(parentDir, normalized),
        path.join(LDRAW_DIR, "parts", normalized),
        path.join(LDRAW_DIR, "p", normalized),
        path.join(LDRAW_DIR, normalized),
      ];
      for (const c of candidates) if (fsSync.existsSync(c)) return c;
      const lower = normalized.toLowerCase();
      if (lower !== normalized) {
        for (const c of [
          path.join(parentDir, lower),
          path.join(LDRAW_DIR, "parts", lower),
          path.join(LDRAW_DIR, "p", lower),
          path.join(LDRAW_DIR, lower),
        ]) if (fsSync.existsSync(c)) return c;
      }
      return null;
    };

    const walk = (absPath: string) => {
      const rel = path.relative(LDRAW_DIR, absPath).replace(/\\/g, "/");
      if (files[rel]) return;
      const content = fsSync.readFileSync(absPath, "utf-8");
      files[rel] = content;
      for (const line of content.split("\n")) {
        const tokens = line.trim().split(/\s+/);
        if (tokens[0] === "1" && tokens.length >= 15) {
          const sub = resolveSub(absPath, tokens.slice(14).join(" "));
          if (sub) walk(sub);
        }
      }
    };

    walk(entry);
    return files;
  }

  registerAppTool(
    server,
    "brick_get_ldraw_files",
    {
      title: "Get LDraw Files",
      description: "Fetch the raw LDraw .dat file for a part plus all its transitive subfile dependencies, for client-side mesh construction.",
      inputSchema: {
        partId: z.string().describe("LDraw part ID (e.g. '3001')"),
      },
      _meta: { ui: { visibility: ["app"] } },
    },
    async ({ partId }) => {
      const files = collectLDrawFiles(partId);
      if (!files) {
        return {
          content: [{ type: "text" as const, text: JSON.stringify({ error: `Part not found: ${partId}` }) }],
          isError: true,
        };
      }
      return {
        content: [{ type: "text" as const, text: JSON.stringify({ files }) }],
      };
    },
  );

  // ── Tool 2d: brick_get_part_info (app-only) ────────────────────────────

  registerAppTool(
    server,
    "brick_get_part_info",
    {
      title: "Get Part Info",
      description: "Get dimensions and metadata for a part by its LDraw ID",
      inputSchema: {
        typeId: z.string().describe("LDraw part ID"),
      },
      _meta: { ui: { visibility: ["app"] } },
    },
    async ({ typeId }) => {
      const def = findBrickType(typeId);
      if (!def) {
        return {
          content: [{ type: "text" as const, text: JSON.stringify({ error: `Unknown part: ${typeId}` }) }],
          isError: true,
        };
      }
      return {
        content: [{ type: "text" as const, text: JSON.stringify(def) }],
      };
    },
  );

  // ── Tool 3: brick_render_scene (model-only, creates frame) ────────────

  registerAppTool(
    server,
    "brick_render_scene",
    {
      title: "Render Brick Scene",
      description: "Opens the 3D brick builder viewer. You MUST call this before brick_place so the user can see the bricks. Call brick_read_me first to learn the brick format.",
      _meta: { ui: { resourceUri } },
    },
    async () => sceneResult("Scene rendered"),
  );

  // ── Tool 4: brick_place (model-facing, no UI metadata) ────────────────

  server.registerTool(
    "brick_place",
    {
      description: `Place one or more bricks. Input is CSV — one brick per line, columns: typeId,x,y,z,rotation,color. Rows are auto-sorted by Y ascending so supports always land before dependents (your CSV order need not be bottom-up). Batch cap: max ${MAX_BATCH_ROWS} rows AND max ${MAX_NEW_TYPES_PER_BATCH} new part types per call — rows beyond either cap are deferred with a clear error (resend them in a follow-up call). Returns a per-row result array: {ok:true, footprint, snappedFrom?} or {ok:false, error, suggestedY?|suggestedX?|suggestedZ?, collidingWith?}. Support failures include suggestedY (nearest valid landing). Collision failures include collidingWith (blocker brick + footprint) and suggestedX/Z (nearest open slot within 8 studs). Bounds failures include suggestedX/Z/Y clamped to valid range. Call brick_render_scene first to open the viewer. Keep batches small (~10 rows) — use the footprints in results to position your next call.`,
      inputSchema: {
        bricks: z.string().describe(
          `CSV, one brick per line. Columns: typeId,x,y,z,rotation,color\n` +
          `  typeId   LDraw part number (e.g. 3001 = Brick 2x4)\n` +
          `  x,y,z    integers — x/z in studs (0..${BASEPLATE_SIZE - 1}), y in plate units (0 = baseplate, +3 per brick layer)\n` +
          `  rotation 0|90|180|270 (optional, default 0)\n` +
          `  color    hex (optional, default #cc0000)\n` +
          `Single brick: one line. Multiple bricks: multiple lines. NO header row.\n` +
          `Example:\n3001,10,0,10,0,#cc0000\n3001,10,0,14,0,#0055bf\n3001,10,3,12,0,#237841`
        ),
      },
    },
    async ({ bricks }) => {
      const lines = bricks.split("\n").map(l => l.trim()).filter(l => l && !l.startsWith("#"));
      if (lines.length === 0) {
        return { content: [{ type: "text" as const, text: JSON.stringify({ error: "No brick rows found in CSV input" }) }], isError: true };
      }

      type Footprint = { minX: number; maxX: number; minZ: number; maxZ: number; topY: number };
      type RowResult =
        | { row: number; ok: true; id: string; typeId: string; position: { x: number; y: number; z: number }; rotation: number; color: string; footprint: Footprint; warnings?: string[]; snappedFrom?: { y: number } }
        | { row: number; ok: false; error: string; line: string; suggestedY?: number; suggestedX?: number; suggestedZ?: number; collidingWith?: { id: string; typeId: string; footprint: Footprint }; snappedFrom?: { y: number } };
      const results: RowResult[] = [];
      const sleep = (ms: number) => new Promise(r => setTimeout(r, ms));

      // Pass 1: parse all rows. Hold parse errors aside; collect valid candidates for Y-sort.
      type ParsedRow = { row: number; line: string; instance: BrickInstance; brickType: BrickDefinition };
      const parseErrors: RowResult[] = [];
      const candidates: ParsedRow[] = [];

      for (let i = 0; i < lines.length; i++) {
        const cols = lines[i].split(",").map(c => c.trim());
        const [typeId, xs, ys, zs, rot, col] = cols;
        const x = parseInt(xs, 10), y = parseInt(ys, 10), z = parseInt(zs, 10);
        const rotation = (rot || "0") as "0" | "90" | "180" | "270";
        const color = col || "#cc0000";

        if (!typeId || !Number.isInteger(x) || !Number.isInteger(y) || !Number.isInteger(z)) {
          parseErrors.push({ row: i + 1, ok: false, error: "Malformed row — need typeId,x,y,z[,rotation,color]", line: lines[i] });
          continue;
        }
        if (!["0", "90", "180", "270"].includes(rotation)) {
          parseErrors.push({ row: i + 1, ok: false, error: `Invalid rotation "${rot}" — must be 0|90|180|270`, line: lines[i] });
          continue;
        }
        const brickType = findBrickType(typeId);
        if (!brickType) {
          parseErrors.push({ row: i + 1, ok: false, error: `Unknown brick type "${typeId}"`, line: lines[i] });
          continue;
        }
        candidates.push({
          row: i + 1, line: lines[i], brickType,
          instance: {
            id: generateId(), typeId, position: { x, y, z },
            rotation: Number(rotation) as 0 | 90 | 180 | 270, color,
          },
        });
      }

      // Pass 2: stable-sort candidates by Y so supports land before dependents.
      // Row indices in results still refer to the original CSV order.
      candidates.sort((a, b) => a.instance.position.y - b.instance.position.y);

      // Track types already in the scene so the new-type cap only counts
      // genuinely novel geometry the client will need to fetch.
      const existingTypes = new Set(scene.bricks.map(b => b.typeId));
      const newTypesThisBatch = new Set<string>();

      let collisionRow: number | null = null;
      let supportFailures = 0;
      let rowsProcessed = 0;
      let capped = false;
      const deferredRows: number[] = [];

      for (const cand of candidates) {
        const { instance, brickType, row, line } = cand;
        const { y } = instance.position;
        const { typeId } = instance;

        // Cap check — applies before validation so deferred rows are known-good
        // parse-wise and can be replayed verbatim in a follow-up call.
        const wouldAddNewType = !existingTypes.has(typeId) && !newTypesThisBatch.has(typeId);
        if (rowsProcessed >= MAX_BATCH_ROWS ||
            (wouldAddNewType && newTypesThisBatch.size >= MAX_NEW_TYPES_PER_BATCH)) {
          capped = true;
          deferredRows.push(row);
          results.push({
            row, ok: false, line,
            error: `Batch cap reached (max ${MAX_BATCH_ROWS} rows, max ${MAX_NEW_TYPES_PER_BATCH} new part types per call). Place this row in a follow-up brick_place call.`,
          });
          continue;
        }

        const boundsErr = checkBounds(instance, brickType);
        if (boundsErr) {
          results.push({
            row, ok: false, error: boundsErr.error, line,
            ...(boundsErr.suggestedX !== undefined ? { suggestedX: boundsErr.suggestedX } : {}),
            ...(boundsErr.suggestedZ !== undefined ? { suggestedZ: boundsErr.suggestedZ } : {}),
            ...(boundsErr.suggestedY !== undefined ? { suggestedY: boundsErr.suggestedY } : {}),
          });
          continue;
        }
        const rowWarnings: string[] = [];
        let snappedFrom: { y: number } | undefined;
        if (!checkSupport(scene.bricks, instance, brickType)) {
          const landingY = findLandingY(instance, brickType);
          if (buildMode === 'relaxed') {
            rowWarnings.push(`floating — no support at y=${y}, nearest landing y=${landingY}`);
          } else if (snapY) {
            snappedFrom = { y };
            instance.position.y = landingY;
            rowWarnings.push(`y auto-snapped ${y}→${landingY}`);
          } else {
            supportFailures++;
            results.push({
              row, ok: false, line, suggestedY: landingY,
              error: `No support at y=${y} — nearest landing is y=${landingY} (use footprint.topY from the brick below)`,
            });
            continue;
          }
        }
        if (checkCollision(scene.bricks, instance, brickType)) {
          if (collisionRow === null) collisionRow = row;
          const blocker = findCollisionBlocker(instance, brickType);
          const scan = scanForOpenSlot(instance, brickType);
          const blockerDesc = blocker
            ? ` — overlaps brick ${blocker.id} (${blocker.typeId}) at footprint {minX:${blocker.footprint.minX},maxX:${blocker.footprint.maxX},minZ:${blocker.footprint.minZ},maxZ:${blocker.footprint.maxZ},topY:${blocker.footprint.topY}}`
            : " — overlaps an existing brick";
          results.push({
            row, ok: false, line,
            error: `Collision${blockerDesc}`,
            ...(blocker ? { collidingWith: blocker } : {}),
            ...(scan.suggestedX !== undefined ? { suggestedX: scan.suggestedX } : {}),
            ...(scan.suggestedZ !== undefined ? { suggestedZ: scan.suggestedZ } : {}),
            ...(snappedFrom ? { snappedFrom, suggestedY: instance.position.y } : {}),
          });
          continue;
        }

        scene.bricks.push(instance);
        grid.place(instance.id, computeOccupiedCells(instance, brickType));
        rowsProcessed++;
        if (wouldAddNewType) newTypesThisBatch.add(typeId);

        const aabb = getBrickAABB(instance, brickType);
        results.push({
          row, ok: true, id: instance.id, typeId: instance.typeId,
          position: { ...instance.position }, rotation: instance.rotation, color: instance.color,
          footprint: { minX: aabb.minX, maxX: aabb.maxX, minZ: aabb.minZ, maxZ: aabb.maxZ, topY: aabb.maxY },
          ...(rowWarnings.length > 0 ? { warnings: rowWarnings } : {}),
          ...(snappedFrom ? { snappedFrom } : {}),
        });

        // Yield to event loop so the widget's 1s poll sees bricks land progressively.
        if (candidates.length > 1) await sleep(60);
      }

      results.push(...parseErrors);
      results.sort((a, b) => a.row - b.row);

      const placed = results.filter(r => r.ok).length;
      const failed = results.length - placed;

      const hints: string[] = [];
      if (capped) {
        deferredRows.sort((a, b) => a - b);
        hints.push(`${deferredRows.length} row(s) deferred to stay under batch limits. Resend those rows in a follow-up brick_place call — they are otherwise valid. Deferred rows: ${deferredRows.join(",")}`);
      }
      if (supportFailures > 0 && collisionRow !== null) {
        hints.push(`Row ${collisionRow} collided — if it was a support brick, rows above it will fail with "no support". Fix the collision first.`);
      }
      if (supportFailures > 1 && collisionRow === null) {
        hints.push(`${supportFailures} rows failed support. Use footprint.topY from the brick below as the next layer's y — don't assume fixed offsets.`);
      }

      return {
        content: [{ type: "text" as const, text: JSON.stringify({
          summary: {
            placed, failed, totalBricks: scene.bricks.length,
            ...(capped ? { deferred: deferredRows.length } : {}),
            ...(hints.length > 0 ? { hints } : {}),
          },
          results,
        }) }],
        isError: placed === 0 && failed > 0,
      };
    },
  );

  // ── Tool 5: brick_get_scene (model-only, no frame) ──────────────────────

  server.registerTool(
    "brick_get_scene",
    {
      description: "Returns the current scene state with all placed bricks and their footprints. Call this ONCE at the start of a building task — between your own brick_place calls, use the footprints in results instead.",
      annotations: { readOnlyHint: true },
    },
    async () => ({
      content: [{ type: "text" as const, text: JSON.stringify({ scene: sceneWithFootprints() }) }],
    }),
  );

  // ── Tool 6: brick_clear_scene (model-facing, no UI metadata) ──────────

  server.registerTool(
    "brick_clear_scene",
    {
      description: "Remove all bricks from the scene.",
      annotations: { destructiveHint: true },
    },
    async () => {
      const count = scene.bricks.length;
      scene.bricks = [];
      grid.clear();
      return sceneResult(`Cleared ${count} bricks`);
    },
  );

  // ── Tool 7: brick_remove_brick (model-facing, no UI metadata) ──────────

  server.registerTool(
    "brick_remove_brick",
    {
      description: "Remove a single brick by its ID. Use brick_get_scene to find brick IDs. Also removes any bricks that lose support as a result.",
      inputSchema: {
        brickId: z.string().describe("ID of the brick to remove (from brick_get_scene or brick_place response)"),
      },
      annotations: { destructiveHint: true },
    },
    async ({ brickId }) => {
      const idx = scene.bricks.findIndex((b) => b.id === brickId);
      if (idx === -1) {
        return {
          content: [{ type: "text" as const, text: JSON.stringify({ error: `Brick not found: "${brickId}". Call brick_get_scene to see current brick IDs.` }) }],
          isError: true,
        };
      }
      const removed = scene.bricks[idx];
      grid.remove(removed.id);
      scene.bricks.splice(idx, 1);
      // Cascade: remove any bricks left unsupported (strict mode only)
      let cascadeCount = 0;
      if (buildMode === 'strict') {
        let changed = true;
        while (changed) {
          changed = false;
          const unsupported = findUnsupported(scene.bricks);
          if (unsupported.length > 0) {
            for (const uid of unsupported) grid.remove(uid);
            scene.bricks = scene.bricks.filter(b => !unsupported.includes(b.id));
            cascadeCount += unsupported.length;
            changed = true;
          }
        }
      }
      const msg = `Removed ${removed.typeId} from (${removed.position.x}, ${removed.position.y}, ${removed.position.z})` +
        (cascadeCount > 0 ? `. Also removed ${cascadeCount} unsupported brick(s) above it.` : "");
      return {
        content: [{ type: "text" as const, text: JSON.stringify({
          removed: { id: removed.id, typeId: removed.typeId, position: removed.position },
          cascadeRemoved: cascadeCount,
          totalBricks: scene.bricks.length,
          message: msg,
        }) }],
      };
    },
  );

  // ── Tool 7b: brick_set_build_mode (model-facing, no UI metadata) ───────

  server.registerTool(
    "brick_set_build_mode",
    {
      description: "Set the build mode and/or snap flag. 'strict' (default): bricks need support, removing a support cascades deletions. 'relaxed': floating bricks allowed (placement returns a warnings hint), no cascade on remove/move/rotate. 'snap': orthogonal flag — when a brick lacks support, auto-correct its y to the nearest landing instead of rejecting. Both fields are optional; either can be set independently.",
      inputSchema: {
        mode: z.enum(["strict", "relaxed"]).optional().describe("Build mode: 'strict' enforces support + cascades, 'relaxed' allows floating bricks and skips cascade deletion."),
        snap: z.boolean().optional().describe(
          "Auto-correct Y to nearest supported landing when a brick would otherwise float. " +
          "Placement succeeds with {snappedFrom:{y:originalY}} in the result. " +
          "If the landed Y also collides, the row fails with a collision error at the landed Y."
        ),
      },
    },
    async ({ mode, snap }) => {
      const previousMode = buildMode;
      const previousSnap = snapY;
      if (mode !== undefined) buildMode = mode;
      if (snap !== undefined) snapY = snap;
      const parts: string[] = [];
      if (mode !== undefined) parts.push(`mode='${buildMode}' (was '${previousMode}')`);
      if (snap !== undefined) parts.push(`snap=${snapY} (was ${previousSnap})`);
      if (parts.length === 0) parts.push(`mode='${buildMode}', snap=${snapY} (no changes)`);
      let message = `Build settings: ${parts.join(", ")}. Scene has ${scene.bricks.length} brick(s).`;
      let floatingCount = 0;
      if (mode === 'strict' && scene.bricks.length > 0) {
        floatingCount = findUnsupported(scene.bricks).length;
        if (floatingCount > 0) {
          message += ` ${floatingCount} floating brick(s) remain — they will not be removed but new placements will require support.`;
        }
      }
      return {
        content: [{ type: "text" as const, text: JSON.stringify({
          mode: buildMode,
          snap: snapY,
          ...(mode !== undefined ? { previousMode } : {}),
          ...(snap !== undefined ? { previousSnap } : {}),
          totalBricks: scene.bricks.length,
          ...(floatingCount > 0 ? { floatingBricks: floatingCount } : {}),
          message,
        }) }],
      };
    },
  );

  // ── Tool 8: brick_export_scene (no frame) ────────────────────────────────

  server.registerTool(
    "brick_export_scene",
    {
      description: "Export the scene as JSON or a summary.",
      inputSchema: {
        format: z.enum(["json", "summary"]).default("summary").describe("Export format"),
      },
      annotations: { readOnlyHint: true },
    },
    async ({ format }) => {
      if (format === "json") {
        return {
          content: [{ type: "text" as const, text: JSON.stringify(scene, null, 2) }],
        };
      }
      // Summary
      const count = scene.bricks.length;
      if (count === 0) {
        return {
          content: [{ type: "text" as const, text: JSON.stringify({ name: scene.name, brickCount: 0 }) }],
        };
      }
      const colorCounts: Record<string, number> = {};
      let minX = Infinity, maxX = -Infinity;
      let minY = Infinity, maxY = -Infinity;
      let minZ = Infinity, maxZ = -Infinity;
      for (const b of scene.bricks) {
        colorCounts[b.color] = (colorCounts[b.color] || 0) + 1;
        const bt = findBrickType(b.typeId);
        if (!bt) continue;
        const aabb = getBrickAABB(b, bt);
        minX = Math.min(minX, aabb.minX); maxX = Math.max(maxX, aabb.maxX);
        minY = Math.min(minY, aabb.minY); maxY = Math.max(maxY, aabb.maxY);
        minZ = Math.min(minZ, aabb.minZ); maxZ = Math.max(maxZ, aabb.maxZ);
      }
      const summary = {
        name: scene.name,
        brickCount: count,
        dimensions: { x: maxX - minX, y: maxY - minY, z: maxZ - minZ },
        colors: colorCounts,
      };
      return { content: [{ type: "text" as const, text: JSON.stringify(summary) }] };
    },
  );

  // ── Tool 9: brick_add (app-only) ────────────────────────────────────────

  registerAppTool(
    server,
    "brick_add",
    {
      title: "Add Brick",
      description: `Add a single brick to the scene. The baseplate is ${BASEPLATE_SIZE}×${BASEPLATE_SIZE} studs. Valid coordinates: x 0–${BASEPLATE_SIZE - 1}, z 0–${BASEPLATE_SIZE - 1}.`,
      inputSchema: {
        typeId: z.string().describe("Brick type ID (LDraw part number)"),
        x: z.number().int().describe(`X position in stud units (0 to ${BASEPLATE_SIZE - 1})`),
        y: z.number().int().min(0).describe("Y position (plate-height units)"),
        z: z.number().int().describe(`Z position in stud units (0 to ${BASEPLATE_SIZE - 1})`),
        rotation: z.enum(["0", "90", "180", "270"]).optional().default("0").describe("Rotation degrees"),
        color: z.string().optional().default("#cc0000").describe("Hex color"),
      },
      _meta: { ui: { visibility: ["app"] } },
    },
    async ({ typeId, x, y, z, rotation, color }) => {
      const brickType = findBrickType(typeId);
      if (!brickType) {
        return { content: [{ type: "text" as const, text: JSON.stringify({ error: `Unknown brick type "${typeId}". Use a valid LDraw part number.` }) }], isError: true };
      }
      const instance: BrickInstance = {
        id: generateId(),
        typeId,
        position: { x, y, z },
        rotation: Number(rotation) as 0 | 90 | 180 | 270,
        color: color ?? "#cc0000",
      };
      const boundsErr = checkBounds(instance, brickType);
      if (boundsErr) {
        return { content: [{ type: "text" as const, text: JSON.stringify({ error: `${typeId} at (${x},${y},${z}): ${boundsErr.error}` }) }], isError: true };
      }
      if (!checkSupport(scene.bricks, instance, brickType)) {
        return { content: [{ type: "text" as const, text: JSON.stringify({ error: `${typeId} at (${x},${y},${z}): no support — must be on baseplate (Y=0) or resting on top of another brick` }) }], isError: true };
      }
      if (checkCollision(scene.bricks, instance, brickType)) {
        return { content: [{ type: "text" as const, text: JSON.stringify({ error: `${typeId} at (${x},${y},${z}): collision — overlaps an existing brick` }) }], isError: true };
      }
      scene.bricks.push(instance);
      grid.place(instance.id, computeOccupiedCells(instance, brickType));
      return sceneResult(`Added ${brickType.name} at (${x}, ${y}, ${z})`);
    },
  );

  // ── Tool 10: brick_remove (app-only) ─────────────────────────────────────

  registerAppTool(
    server,
    "brick_remove",
    {
      title: "Remove Brick",
      description: "Remove a brick by its ID.",
      inputSchema: {
        brickId: z.string().describe("ID of the brick to remove"),
      },
      _meta: { ui: { visibility: ["app"] } },
    },
    async ({ brickId }) => {
      const idx = scene.bricks.findIndex((b) => b.id === brickId);
      if (idx === -1) {
        return { content: [{ type: "text" as const, text: JSON.stringify({ error: `Brick not found: "${brickId}". It may have already been removed. Call brick_get_scene to see current bricks.` }) }], isError: true };
      }
      const removed = scene.bricks[idx];
      grid.remove(removed.id);
      scene.bricks.splice(idx, 1);
      // Cascade: remove any bricks left unsupported (strict mode only)
      let cascadeCount = 0;
      if (buildMode === 'strict') {
        let changed = true;
        while (changed) {
          changed = false;
          const unsupported = findUnsupported(scene.bricks);
          if (unsupported.length > 0) {
            for (const uid of unsupported) grid.remove(uid);
            scene.bricks = scene.bricks.filter(b => !unsupported.includes(b.id));
            cascadeCount += unsupported.length;
            changed = true;
          }
        }
      }

      const msg = `Removed ${removed.typeId} from (${removed.position.x}, ${removed.position.y}, ${removed.position.z})` +
        (cascadeCount > 0 ? `. Also removed ${cascadeCount} unsupported brick(s) above it.` : "");
      return sceneResult(msg);
    },
  );

  // ── Tool 11: brick_move (app-only) ───────────────────────────────────────

  registerAppTool(
    server,
    "brick_move",
    {
      title: "Move Brick",
      description: "Move a brick to a new position.",
      inputSchema: {
        brickId: z.string().describe("ID of the brick to move"),
        x: z.number().int().describe("New X position"),
        y: z.number().int().min(0).describe("New Y position"),
        z: z.number().int().describe("New Z position"),
      },
      _meta: { ui: { visibility: ["app"] } },
    },
    async ({ brickId, x, y, z }) => {
      const brick = scene.bricks.find((b) => b.id === brickId);
      if (!brick) {
        return { content: [{ type: "text" as const, text: JSON.stringify({ error: `Brick not found: "${brickId}". It may have been removed. Call brick_get_scene to see current bricks.` }) }], isError: true };
      }
      const brickType = findBrickType(brick.typeId);
      if (!brickType) {
        return { content: [{ type: "text" as const, text: JSON.stringify({ error: `Invalid brick type "${brick.typeId}" on brick ${brickId}.` }) }], isError: true };
      }
      const moved: BrickInstance = { ...brick, position: { x, y, z } };
      const boundsErr = checkBounds(moved, brickType);
      if (boundsErr) {
        return { content: [{ type: "text" as const, text: JSON.stringify({ error: `Cannot move ${brick.typeId} to (${x},${y},${z}): ${boundsErr.error}` }) }], isError: true };
      }
      // Temporarily remove from grid to check support/collision at new position
      grid.remove(brickId);
      if (!checkSupport(scene.bricks.filter(b => b.id !== brickId), moved, brickType)) {
        grid.place(brickId, computeOccupiedCells(brick, brickType)); // restore
        return { content: [{ type: "text" as const, text: JSON.stringify({ error: `Cannot move ${brick.typeId} to (${x},${y},${z}): no support — must be on baseplate (Y=0) or resting on top of another brick` }) }], isError: true };
      }
      if (checkCollision(scene.bricks, moved, brickType, brickId)) {
        grid.place(brickId, computeOccupiedCells(brick, brickType)); // restore
        return { content: [{ type: "text" as const, text: JSON.stringify({ error: `Cannot move ${brick.typeId} to (${x},${y},${z}): collision — overlaps an existing brick` }) }], isError: true };
      }
      const oldPos = { ...brick.position };
      brick.position = { x, y, z };
      grid.place(brickId, computeOccupiedCells(brick, brickType));
      // Cascade: remove any bricks left unsupported by this move (strict mode only)
      let cascadeCount = 0;
      if (buildMode === 'strict') {
        let changed = true;
        while (changed) {
          changed = false;
          const unsupported = findUnsupported(scene.bricks);
          if (unsupported.length > 0) {
            for (const uid of unsupported) grid.remove(uid);
            scene.bricks = scene.bricks.filter(b => !unsupported.includes(b.id));
            cascadeCount += unsupported.length;
            changed = true;
          }
        }
      }

      const msg = `Moved ${brick.typeId} from (${oldPos.x},${oldPos.y},${oldPos.z}) to (${x}, ${y}, ${z})` +
        (cascadeCount > 0 ? `. Removed ${cascadeCount} unsupported brick(s) that were above old position.` : "");
      return sceneResult(msg);
    },
  );

  // ── Tool 12: brick_rotate (app-only) ────────────────────────────────────

  registerAppTool(
    server,
    "brick_rotate",
    {
      title: "Rotate Brick",
      description: "Set a brick's rotation.",
      inputSchema: {
        brickId: z.string().describe("ID of the brick to rotate"),
        rotation: z.enum(["0", "90", "180", "270"]).describe("New rotation in degrees"),
      },
      _meta: { ui: { visibility: ["app"] } },
    },
    async ({ brickId, rotation }) => {
      const brick = scene.bricks.find((b) => b.id === brickId);
      if (!brick) {
        return { content: [{ type: "text" as const, text: JSON.stringify({ error: `Brick not found: "${brickId}". It may have been removed. Call brick_get_scene to see current bricks.` }) }], isError: true };
      }
      const brickType = findBrickType(brick.typeId);
      if (!brickType) {
        return { content: [{ type: "text" as const, text: JSON.stringify({ error: `Invalid brick type "${brick.typeId}" on brick ${brickId}.` }) }], isError: true };
      }
      const rotated: BrickInstance = { ...brick, rotation: Number(rotation) as 0 | 90 | 180 | 270 };
      const boundsErr = checkBounds(rotated, brickType);
      if (boundsErr) {
        return { content: [{ type: "text" as const, text: JSON.stringify({ error: `Cannot rotate ${brick.typeId} at (${brick.position.x},${brick.position.y},${brick.position.z}) to ${rotation}°: ${boundsErr.error}` }) }], isError: true };
      }
      // Temporarily remove from grid to check support/collision with new rotation
      grid.remove(brickId);
      // Check self-support after rotation (footprint changes)
      if (!checkSupport(scene.bricks.filter(b => b.id !== brickId), rotated, brickType)) {
        grid.place(brickId, computeOccupiedCells(brick, brickType)); // restore
        return { content: [{ type: "text" as const, text: JSON.stringify({ error: `Cannot rotate ${brick.typeId} at (${brick.position.x},${brick.position.y},${brick.position.z}) to ${rotation}°: no support after rotation — brick would float` }) }], isError: true };
      }
      if (checkCollision(scene.bricks, rotated, brickType, brickId)) {
        grid.place(brickId, computeOccupiedCells(brick, brickType)); // restore
        return { content: [{ type: "text" as const, text: JSON.stringify({ error: `Cannot rotate ${brick.typeId} at (${brick.position.x},${brick.position.y},${brick.position.z}) to ${rotation}°: collision — overlaps an existing brick` }) }], isError: true };
      }
      brick.rotation = Number(rotation) as 0 | 90 | 180 | 270;
      grid.place(brickId, computeOccupiedCells(brick, brickType));
      // Cascade: remove any bricks left unsupported by the footprint change (strict mode only)
      let cascadeCount = 0;
      if (buildMode === 'strict') {
        let changed = true;
        while (changed) {
          changed = false;
          const unsupported = findUnsupported(scene.bricks);
          if (unsupported.length > 0) {
            for (const uid of unsupported) grid.remove(uid);
            scene.bricks = scene.bricks.filter(b => !unsupported.includes(b.id));
            cascadeCount += unsupported.length;
            changed = true;
          }
        }
      }

      const msg = `Rotated ${brick.typeId} at (${brick.position.x}, ${brick.position.y}, ${brick.position.z}) to ${rotation}°` +
        (cascadeCount > 0 ? `. Removed ${cascadeCount} unsupported brick(s) above.` : "");
      return sceneResult(msg);
    },
  );

  // ── Tool 13: brick_paint (app-only) ─────────────────────────────────────

  registerAppTool(
    server,
    "brick_paint",
    {
      title: "Paint Brick",
      description: "Change a brick's color.",
      inputSchema: {
        brickId: z.string().describe("ID of the brick to paint"),
        color: z.string().describe("New hex color"),
      },
      _meta: { ui: { visibility: ["app"] } },
    },
    async ({ brickId, color }) => {
      const brick = scene.bricks.find((b) => b.id === brickId);
      if (!brick) {
        return { content: [{ type: "text" as const, text: JSON.stringify({ error: `Brick not found: "${brickId}". It may have been removed. Call brick_get_scene to see current bricks.` }) }], isError: true };
      }
      brick.color = color;
      return sceneResult(`Painted ${brick.typeId} at (${brick.position.x}, ${brick.position.y}, ${brick.position.z}) → ${color}`);
    },
  );

  // ── Tool 14: brick_set_camera (app-only) ────────────────────────────────

  registerAppTool(
    server,
    "brick_set_camera",
    {
      title: "Set Camera",
      description: "Set the camera position and look-at target.",
      inputSchema: {
        posX: z.number().describe("Camera X position"),
        posY: z.number().describe("Camera Y position"),
        posZ: z.number().describe("Camera Z position"),
        targetX: z.number().optional().default(0).describe("Look-at X"),
        targetY: z.number().optional().default(0).describe("Look-at Y"),
        targetZ: z.number().optional().default(0).describe("Look-at Z"),
      },
      _meta: { ui: { visibility: ["app"] } },
    },
    async ({ posX, posY, posZ, targetX, targetY, targetZ }) => {
      const payload = {
        scene,
        camera: {
          position: { x: posX, y: posY, z: posZ },
          target: { x: targetX ?? 0, y: targetY ?? 0, z: targetZ ?? 0 },
        },
        message: "Camera updated",
      };
      return { content: [{ type: "text" as const, text: JSON.stringify(payload) }] };
    },
  );

  // ── Tool 15: brick_import_scene (app-only) ──────────────────────────────

  registerAppTool(
    server,
    "brick_import_scene",
    {
      title: "Import Scene",
      description: "Import a scene from JSON.",
      inputSchema: {
        sceneJson: z.string().describe("Scene JSON string"),
      },
      _meta: { ui: { visibility: ["app"] } },
    },
    async ({ sceneJson }) => {
      try {
        const imported = JSON.parse(sceneJson);
        if (!imported.name || !Array.isArray(imported.bricks)) {
          return { content: [{ type: "text" as const, text: JSON.stringify({ error: 'Invalid scene format — expected { "name": "...", "bricks": [...] }' }) }], isError: true };
        }
        // Validate all bricks: sort by Y and re-add with full validation
        const raw: BrickInstance[] = imported.bricks;
        const sorted = [...raw].sort((a, b) => a.position.y - b.position.y);
        const valid: BrickInstance[] = [];
        grid.clear();
        let dropped = 0;
        for (const brick of sorted) {
          const bt = findBrickType(brick.typeId);
          if (!bt) { dropped++; continue; }
          if (checkBounds(brick, bt)) { dropped++; continue; }
          if (buildMode === 'strict' && !checkSupport(valid, brick, bt)) { dropped++; continue; }
          if (checkCollision(valid, brick, bt)) { dropped++; continue; }
          valid.push(brick);
          grid.place(brick.id, computeOccupiedCells(brick, bt));
        }
        scene = { name: imported.name, bricks: valid };
        const msg = `Imported scene '${scene.name}' with ${valid.length} bricks` +
          (dropped > 0 ? ` (dropped ${dropped} invalid/floating/colliding bricks)` : "");
        return sceneResult(msg);
      } catch (e) {
        return { content: [{ type: "text" as const, text: JSON.stringify({ error: `Invalid JSON: ${e instanceof Error ? e.message : "parse error"}` }) }], isError: true };
      }
    },
  );

  // ── Tool 16: brick_set_scene_name (app-only) ────────────────────────────

  registerAppTool(
    server,
    "brick_set_scene_name",
    {
      title: "Set Scene Name",
      description: "Set the scene's display name.",
      inputSchema: {
        name: z.string().describe("New scene name"),
      },
      _meta: { ui: { visibility: ["app"] } },
    },
    async ({ name }) => {
      scene.name = name;
      return sceneResult(`Scene renamed to '${name}'`);
    },
  );

  // ── Resource registration ───────────────────────────────────────────────

  registerAppResource(
    server,
    resourceUri,
    resourceUri,
    { mimeType: RESOURCE_MIME_TYPE, description: "Brick Builder UI" },
    async (): Promise<ReadResourceResult> => {
      const html = await fs.readFile(path.join(DIST_DIR, "mcp-app.html"), "utf-8");
      return {
        contents: [{ uri: resourceUri, mimeType: RESOURCE_MIME_TYPE, text: html }],
      };
    },
  );

  return server;
}
