#!/usr/bin/env tsx
/**
 * bundle-ldraw.ts
 *
 * Reads all files from the ldraw/ directory and generates a TypeScript module
 * that embeds them as string constants. This allows the LDraw data to be
 * included in the single-file Vite bundle for the MCP app.
 *
 * Output: src/ldraw/ldraw-bundle.ts
 */

import fs from 'node:fs';
import path from 'node:path';

const LDRAW_DIR = path.resolve(import.meta.dirname, '..', 'ldraw');
const OUT_FILE = path.resolve(import.meta.dirname, '..', 'src', 'ldraw', 'ldraw-bundle.ts');

function collectFiles(dir: string, base: string): Record<string, string> {
  const result: Record<string, string> = {};

  if (!fs.existsSync(dir)) {
    console.warn(`WARNING: ldraw/ directory not found at ${dir}`);
    console.warn('Run scripts/extract-ldraw-subset.ts first, or the app will use procedural fallback geometry.');
    return result;
  }

  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    const relativePath = base ? `${base}/${entry.name}` : entry.name;

    if (entry.isDirectory()) {
      Object.assign(result, collectFiles(fullPath, relativePath));
    } else if (entry.isFile() && (entry.name.endsWith('.dat') || entry.name.endsWith('.ldr'))) {
      result[relativePath] = fs.readFileSync(fullPath, 'utf-8');
    }
  }

  return result;
}

function main() {
  const files = collectFiles(LDRAW_DIR, '');
  const fileCount = Object.keys(files).length;

  if (fileCount === 0) {
    // Generate empty bundle so the build doesn't fail
    const content = `// Auto-generated by scripts/bundle-ldraw.ts — no LDraw files found
// Run scripts/extract-ldraw-subset.ts to populate ldraw/ directory
export const LDRAW_FILES: Record<string, string> = {};
`;
    fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
    fs.writeFileSync(OUT_FILE, content);
    console.log('Generated empty ldraw-bundle.ts (no LDraw files found)');
    return;
  }

  // Build the module
  let content = `// Auto-generated by scripts/bundle-ldraw.ts — DO NOT EDIT\n`;
  content += `// Contains ${fileCount} embedded LDraw files\n`;
  content += `export const LDRAW_FILES: Record<string, string> = {\n`;

  for (const [filePath, fileContent] of Object.entries(files)) {
    // Use JSON.stringify to properly escape the file content
    content += `  ${JSON.stringify(filePath)}: ${JSON.stringify(fileContent)},\n`;
  }

  content += `};\n`;

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, content);
  console.log(`Generated ldraw-bundle.ts with ${fileCount} files`);
}

main();
